quarkus.http.port=8080
quarkus.rest-client.fake-payment-provider.url=http://localhost:8081
quarkus.rest-client.fake-payment-provider.connect-timeout=500
quarkus.rest-client.fake-payment-provider.read-timeout=5000
quarkus.log.category."io.smallrye.faulttolerance".level=DEBUG
